---
- name: update apt
  apt: update_cache=yes


- name: Install smaller software packages
  apt: name={{ item }} state=present
  with_items:
    - bc
    - nginx

- name: Get letsencrypt 
  git:
    accept_hostkey: True
    dest: "{{encrypt_client_location}}"
    force: yes
    update: yes
    repo: https://github.com/letsencrypt/letsencrypt